spring:
  application:
    name:
      MoneyFi-budget
  datasource:
    url: jdbc:sqlserver://gowri5877server.database.windows.net:1433;database=moneyfi_db;user=gowri@gowri5877server;password=password;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    # username: ${RDS_USERNAME:sa}
    # password: ${RDS_PASSWORD:admin@123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port:
    8300
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://20.248.125.223:8761/eureka
  instance:
    prefer-ip-address: true
