spring:
  application:
    name:
      MoneyFi-budget
  datasource:
    url: jdbc:sqlserver://gowri5877server.database.windows.net:1433;database=moneyfi_db;user=gowri@gowri5877server;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    # username: ${RDS_USERNAME:sa}
    # password: ${RDS_PASSWORD:admin@123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port:
    8300
